name = "Attenuations"
uuid = "0ff343a0-c53e-11e9-1400-85e187be3184"
authors = ["Kevin C. Zimmerman <kevinczimmerman@gmail.com>", "Dale Black <djblack@uci.edu>"]
version = "0.7.0"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AxisArrays = "0.4"
HTTP = "1"
Unitful = "1"
julia = "1.10, 1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
